name = "game-club"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "game-club"
database_id = "fcc5645d-d485-4df3-927b-d83048ed2f33"
migrations_dir = "migrations"
